# Settings in the [build] context are global and are applied to 
# all contexts unless otherwise overridden by more specific contexts.
[build]
  base    = ''
  command = "npx chromatic --project-token=b99f26184a32 --exit-once-uploaded"